#!/bin/sh
#
# Copyright (C) 2020 Dusan Mitrovic <dusan@dusanmitrovic.xyz>
# Licensed under the terms of the GNU GPL v3 only
#
# i3blocks script to get the battery information
battery="/sys/class/power_supply/BAT?"

state=$(cat $battery/status)
capacity=$(cat $battery/capacity | sed "s/$/%/g")

[ $state = "Discharging" ] && icon="🔋"
[ $state = "Charging" ] && icon="🔌"
[ $state = "Full" ] && icon="⚡"

echo "$icon $capacity"
