#!/bin/sh
#
# Copyright (C) 2020 Dusan Mitrovic <dusan@dusanmitrovic.xyz>
# Licensed under the terms of the GNU GPL v3 only
#
# i3blocks script to get the battery information
state=`acpi | awk '/^Battery/ {print $3}'`
percentage=`acpi | awk '/^Battery/ {print $4}'`
if [ "$state" = "Charging," ]; then
    echo  ${percentage/%?/}
else
    echo  ${percentage/%?/}
fi
