#!/bin/sh
#
# Copyright (C) 2020 Dusan Mitrovic <dusan@dusanmitrovic.xyz>
# Licensed under the terms of the GNU GPL v3 only
#
# i3blocks script to get the CPU temperature
icon="📈"

echo "$icon $(sensors | grep temp1 | awk '{print $2}' | sed "s/^.//g")"
