#!/bin/sh
#
# Copyright (C) 2020 Dusan Mitrovic <dusan@dusanmitrovic.xyz>
# Licensed under the terms of the GNU GPL v3 only
#
# i3blocks script to display the current keyboard layout
current_layout=$(setxkbmap -query | awk '/^layout/ {print $2}')

[ $current_layout = "us" ] && flag="🇺🇸"
[ $current_layout = "rs" ] && flag="🇷🇸"

echo "$flag $current_layout"
