#!/bin/bash
#
# Copyright (C) 2020 Dusan Mitrovic <dusan@dusanmitrovic.xyz>
# Licensed under the terms of the GNU GPL v3 only
#
# i3blocks script to get the RAM information
case $BLOCK_BUTTON in
	1) notify-send "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
esac

free -h | awk '/^Mem/ {print $3 "/" $2}'
