#!/bin/sh
#
# Copyright (C) 2020 Dusan Mitrovic <dusan@dusanmitrovic.xyz>
# Licensed under the terms of the GNU GPL v3 only
#
# i3blocks script to get the now playing information from MPD, runs ncmpcpp on click
TRACK=$(mpc | awk 'NR==1')
STATE=$(mpc | awk 'NR==2 {print $1}')

case $STATE in
    "[paused]") echo "$TRACK $STATE";;
    "[playing]") echo $TRACK;;
esac

case $BLOCK_BUTTON in
    1) $TERMINAL -e ncmpcpp;;
esac
