#!/bin/sh
#
# Copyright (C) 2020 Dusan Mitrovic <dusan@dusanmitrovic.xyz>
# Licensed under the terms of the GNU GPL, version 3 only
#
# i3blocks script to show the time
icon="⏳"

echo "$icon $(date '+%H:%M:%S')"
