#!/bin/bash
#
# Copyright (C) 2020 Dusan Mitrovic <dusan@dusanmitrovic.xyz>
# Licensed under the terms of the GNU GPL v3 only
#
# i3blocks script to get and control system volume
case $BLOCK_BUTTON in
	1) setsid pavucontrol ;;
	3) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +5 ;;
	5) pulsemixer --change-volume -5 ;;
esac

[ "$(pulsemixer --get-mute)" = "1" ] && printf "🔇\\n" && exit

vol=$(pulsemixer --get-volume | awk '{print $2}')

[ $vol -le 35 ] && icon="🔈"
[ $vol -ge 35 ] && [ $vol -le 70 ] && icon="🔉"
[ $vol -ge 70 ] && icon="🔊"

echo "$icon $vol" | sed "s/$/%/g"
