#!/bin/bash
#
# Copyright (C) 2020 Dusan Mitrovic <dusan@dusanmitrovic.xyz>
# Licensed under the terms of the GNU GPL v3 only
#
# i3blocks script to get the current weather conditions and temperature from openweathermap.org
# Depends on json2tsv <https://pypi.org/project/json2tsv/>
[ ! -f /usr/bin/json2tsv ] && exit 1

api_url="https://api.openweathermap.org/data/2.5/weather"
city_id="787516"
webpage="https://openweathermap.org/city/$city_id"
icon="🌤"

json=$(curl -s -X GET "$api_url?id=$city_id&units=metric&appid=$OPENWEATHER_API_KEY")

temperature="$(echo $json | json2tsv main.temp | awk '{printf "%.1f", $1}')°C"
conditions=$(echo $json | json2tsv weather | json2tsv main)

case $BLOCK_BUTTON in
    1) firefox -new-tab $webpage & ;;
esac

echo "$icon $temperature $conditions"
