#!/usr/bin/bash

COMIC_BOOK_DIRECTORY="$HOME/Documents/Comics"

CHOICE=`ls $COMIC_BOOK_DIRECTORY | dmenu -i -h 20 -p "Choose what to read:"`

if [ -n "$CHOICE" ]; then
    COMIC_CHOICE=`locate "$COMIC_BOOK_DIRECTORY/$CHOICE" | grep -E ".*\.(cbr|cbz|cb7)" | dmenu -i -c -h 20 -l 30 -p "Choose an issue:"`

    if [ -n "$COMIC_CHOICE" ]; then
        zathura "$COMIC_CHOICE"
    fi
fi
