#!/bin/bash

SCREENSHOT="/tmp/screen.png"

[[ -f $SCREENSHOT ]] && rm $SCREENSHOT

scrot $SCREENSHOT

[[ -f ~/.config/i3/lockicon.png  ]] && convert $SCREENSHOT -swirl 360 ~/.config/i3/lockicon.png -gravity center -composite -matte $SCREENSHOT

i3lock -e -f -c 000000 -i $SCREENSHOT
