#!/bin/bash

scrot /tmp/screen.png

[[ -f ~/.config/i3/lockicon.png  ]] && convert /tmp/screen.png -swirl 360 ~/.config/i3/lockicon.png -gravity center -composite -matte /tmp/screen.png

i3lock -e -f -c 000000 -i /tmp/screen.png
