#!/bin/sh

pgrep -x transmission-da >/dev/null || (transmission-daemon && notify-send "Starting transmission daemon..." && sleep 3)

transmission-remote -w ~/Downloads/Torrents -a "$@" && notify-send "✔ Torrent added."
