#!/bin/bash

case $BLOCK_BUTTON in
	1) setsid pavucontrol ;;
	3) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +5 ;;
	5) pulsemixer --change-volume -5 ;;
esac

[ "$(pulsemixer --get-mute)" = "1" ] && printf "🔇\\n" && exit

vol=$(pulsemixer --get-volume | awk '{print $1}')

printf "%s %s%%\\n" "" "$vol"

